ALTER SESSION SET CURRENT_SCHEMA = QLTHUVIEN_21120344;

CREATE OR REPLACE PROCEDURE USP_QLTV_TAOTK_DOCGIA 
AS 
    CURSOR CUR IS (
        SELECT MADOCGIA FROM DOCGIA 
        WHERE MADOCGIA NOT IN (
            SELECT USERNAME FROM ALL_USERS
        )
    );
    STRSQL VARCHAR(2000); 
    USR VARCHAR2(10) ;
BEGIN 
    OPEN CUR ; 
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE' ;
    
    EXECUTE IMMEDIATE(STRSQL) ; 
    
    LOOP 
        FETCH CUR INTO USR ; 
        EXIT WHEN CUR%NOTFOUND; 
        
        STRSQL := 'CREATE USER ' || USR || ' IDENTIFIED BY 123';
        EXECUTE IMMEDIATE(STRSQL) ; 
        STRSQL := 'GRANT CONNECT TO ' || USR ;
        EXECUTE IMMEDIATE (STRSQL); 
    END LOOP; 
    
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE' ; 
    EXECUTE IMMEDIATE (STRSQL) ; 
    CLOSE CUR ;
END ; 
/

EXEC USP_QLTV_TAOTK_DOCGIA; 
/

CREATE OR REPLACE PROCEDURE USP_QLTV_TAOTK_NHANVIEN 
AS 
    STRSQL VARCHAR2(2000); 
    USR VARCHAR2(10) ; 
    CURSOR CUR IS (
        SELECT MANHANVIEN FROM NHANVIEN 
        WHERE MANHANVIEN NOT IN (
            SELECT USERNAME FROM ALL_USERS
        ) 
    ); 
BEGIN 
    OPEN CUR ; 
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE'; 
    EXECUTE IMMEDIATE (STRSQL) ; 
    
    LOOP 
        FETCH CUR INTO USR ;
        EXIT WHEN CUR%NOTFOUND; 
        
        STRSQL := 'CREATE USER ' || USR || ' IDENTIFIED BY 123'; 
        EXECUTE IMMEDIATE (STRSQL) ; 
        STRSQL := 'GRANT CONNECT TO ' || USR ;
        EXECUTE IMMEDIATE (STRSQL); 
        
    END LOOP ;
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE' ; 
    EXECUTE IMMEDIATE (STRSQL) ; 
    CLOSE CUR ;
END ; 
/ 
EXEC USP_QLTV_TAOTK_NHANVIEN;