ALTER SESSION SET CURRENT_SCHEMA = QLTHUVIEN_21120344;

-- XEM LAI CAC PHIEU MUON SACH DA MUON
--COT
CREATE OR REPLACE VIEW UV_QLTV_XEMPHIEUMUONSACH 
AS 
    SELECT PMS.MAPHIEUMUONSACH, PMS.MADOCGIA, PMS.SOLUONG AS SOLUONGPHIEU, CT_PMS.MASACH, S.TENSACH, CT_PMS.SOLUONG
    FROM PHIEUMUONSACH PMS, CHITIETPHIEUMUON CT_PMS, SACH S 
    WHERE 
        PMS.MAPHIEUMUONSACH = CT_PMS.MAPHIEUMUONSACH AND
        CT_PMS.MASACH = S.MASACH 
;
/
--DONG
CREATE OR REPLACE VIEW UV_QLTV_XEMPHIEUMUONSACH_DOCGIA
AS 
SELECT * FROM UV_QLTV_XEMPHIEUMUONSACH 
WHERE MADOCGIA = SYS_CONTEXT('USERENV', 'SESSION_USER') ;  
/
-- XEM THONG TIN TAI KHOAN CUA DOC GIA 
--DONG
CREATE OR REPLACE VIEW UV_QLTV_XEMTK_DOCGIA 
AS 
    SELECT * FROM DOCGIA 
    WHERE MADOCGIA = SYS_CONTEXT('USERENV', 'SESSION_USER') ; 
/ 

--XEM THONG TIN CA NHAN CUA NHAN VIEN 
--DONG
CREATE OR REPLACE VIEW UV_QLTV_XEMTK_NHANVIEN
AS 
    SELECT * FROM NHANVIEN
    WHERE MANHANVIEN = SYS_CONTEXT('USERENV', 'SESSION_USER') ; 
/

--XEM CAC PHIEU MUON CUA THU VIEN MINH

CREATE OR REPLACE VIEW UV_QLTV_XEMPHIEUMUON_THUTHU 
AS 
    SELECT * FROM PHIEUMUONSACH 
    WHERE MATHUVIEN =  (
        SELECT MATHUVIEN 
        FROM NHANVIEN 
        WHERE MANHANVIEN = SYS_CONTEXT('USERENV', 'SESSION_USER') 
    ) ;
/

--XEM CAC PHIEU MUON MA THU THU DA KY 
CREATE OR REPLACE VIEW UV_QLTV_XEMTT_PHIEUMUON_THUTHU
AS 
    SELECT * FROM CHITIETPHIEUMUON 
    WHERE MAPHIEUMUONSACH IN (
        SELECT MAPHIEUMUONSACH 
        FROM QLTHUVIEN_21120344.UV_QLTV_XEMPHIEUMUON_THUTHU 
    )
; 
/

-- NHAN VIEN QUAN LY XEM THONG TIN THU THU 
CREATE OR REPLACE VIEW UV_QLTV_XEMTHUTHU 
AS
    SELECT MANHANVIEN , MATHUVIEN, LOAINHANVIEN, HOTEN , NGAYSINH , SODIENTHOAI, EMAIL
    FROM NHANVIEN 
    WHERE LOAINHANVIEN = (
        SELECT MALOAINHANVIEN FROM LOAINHANVIEN 
        WHERE TENLOAINHANVIEN = 'TH? TH?'
    )
;
/

-- XEM THONG TIN THU THU TRONG THU VIEN MINH QUAN LY 
CREATE OR REPLACE VIEW UV_QLTV_XEMTT_THUTHU
AS 
SELECT * FROM UV_QLTV_XEMTHUTHU 
WHERE MATHUVIEN = (
    SELECT MATHUVIEN FROM NHANVIEN 
    WHERE MANHANVIEN = SYS_CONTEXT('USERENV', 'SESSION_USER') 
    AND LOAINHANVIEN = 'QL'
)
;
/